import { Domain, Question } from '@/types'

export const DOMAIN_META: Record<Domain, {
  label: string
  description: string
  weight: number
  colorClass: string
  bgClass: string
  borderClass: string
  badgeClass: string
}> = {
  finance: {
    label: 'Finance',
    description: 'Financial health, records & compliance',
    weight: 0.40,
    colorClass: 'text-blue-700',
    bgClass: 'bg-blue-50',
    borderClass: 'border-blue-200',
    badgeClass: 'bg-blue-100 text-blue-800',
  },
  operations: {
    label: 'Operations',
    description: 'Processes, equipment, staff & compliance',
    weight: 0.25,
    colorClass: 'text-amber-700',
    bgClass: 'bg-amber-50',
    borderClass: 'border-amber-200',
    badgeClass: 'bg-amber-100 text-amber-800',
  },
  sales: {
    label: 'Sales',
    description: 'Pipeline, customers & conversion',
    weight: 0.20,
    colorClass: 'text-emerald-700',
    bgClass: 'bg-emerald-50',
    borderClass: 'border-emerald-200',
    badgeClass: 'bg-emerald-100 text-emerald-800',
  },
  marketing: {
    label: 'Marketing',
    description: 'Online presence & lead generation',
    weight: 0.15,
    colorClass: 'text-purple-700',
    bgClass: 'bg-purple-50',
    borderClass: 'border-purple-200',
    badgeClass: 'bg-purple-100 text-purple-800',
  },
}

export const QUESTIONS: Question[] = [
  // ── FINANCE ──────────────────────────────────────────────────────────────
  {
    id: 'fin_revenue_trend',
    domain: 'finance',
    category: 'Revenue',
    label: 'Revenue trend over last 3 years',
    type: 'rating',
    helpText: '1 = Declining significantly  ·  5 = Growing strongly (>20% YoY)',
    weight: 3,
  },
  {
    id: 'fin_revenue_amount',
    domain: 'finance',
    category: 'Revenue',
    label: 'Approximate annual revenue (AUD)',
    type: 'number',
    helpText: 'Most recent full-year revenue figure',
    weight: 0,
  },
  {
    id: 'fin_gross_margin',
    domain: 'finance',
    category: 'Profitability',
    label: 'Gross margin assessment',
    type: 'rating',
    helpText: '1 = <10% (very thin)  ·  5 = >40% (strong)',
    weight: 3,
  },
  {
    id: 'fin_gross_margin_pct',
    domain: 'finance',
    category: 'Profitability',
    label: 'Gross margin %',
    type: 'number',
    helpText: 'Approximate gross margin percentage',
    weight: 0,
  },
  {
    id: 'fin_net_margin',
    domain: 'finance',
    category: 'Profitability',
    label: 'Net profit margin assessment',
    type: 'rating',
    helpText: '1 = Losses  ·  5 = >15% net margin',
    weight: 2,
  },
  {
    id: 'fin_cashflow',
    domain: 'finance',
    category: 'Cash Flow',
    label: 'Monthly cash flow position',
    type: 'rating',
    helpText: '1 = Consistently negative  ·  5 = Consistently positive with buffer',
    weight: 3,
  },
  {
    id: 'fin_debtor_days',
    domain: 'finance',
    category: 'Cash Flow',
    label: 'Debtor days management',
    type: 'rating',
    helpText: '1 = >90 days (poor collection)  ·  5 = <30 days (excellent)',
    weight: 2,
  },
  {
    id: 'fin_debtor_days_value',
    domain: 'finance',
    category: 'Cash Flow',
    label: 'Average debtor days',
    type: 'number',
    helpText: 'How many days on average to collect payment',
    weight: 0,
  },
  {
    id: 'fin_existing_debt',
    domain: 'finance',
    category: 'Debt',
    label: 'Current debt serviceability',
    type: 'rating',
    helpText: '1 = Over-leveraged / struggling  ·  5 = No debt or easily serviceable',
    weight: 3,
  },
  {
    id: 'fin_existing_debt_amount',
    domain: 'finance',
    category: 'Debt',
    label: 'Total existing debt (AUD)',
    type: 'number',
    helpText: 'All loans, equipment finance, credit cards',
    weight: 0,
  },
  {
    id: 'fin_record_quality',
    domain: 'finance',
    category: 'Records',
    label: 'Quality of financial records',
    type: 'rating',
    helpText: '1 = No formal records  ·  5 = Fully reconciled, reviewed accounts',
    weight: 3,
  },
  {
    id: 'fin_accounting_software',
    domain: 'finance',
    category: 'Records',
    label: 'Accounting software in use',
    type: 'text',
    helpText: 'e.g. Xero, MYOB, QuickBooks, spreadsheets, none',
    weight: 0,
  },
  {
    id: 'fin_accountant',
    domain: 'finance',
    category: 'Records',
    label: 'Uses a qualified accountant or bookkeeper',
    type: 'yesno',
    weight: 2,
  },
  {
    id: 'fin_tax_compliance',
    domain: 'finance',
    category: 'Compliance',
    label: 'Tax & ATO obligations up to date',
    type: 'yesno',
    weight: 2,
  },
  {
    id: 'fin_bas',
    domain: 'finance',
    category: 'Compliance',
    label: 'BAS lodgements current',
    type: 'yesno',
    weight: 2,
  },

  // ── OPERATIONS ────────────────────────────────────────────────────────────
  {
    id: 'ops_project_mgmt',
    domain: 'operations',
    category: 'Process',
    label: 'Project management system in use',
    type: 'rating',
    helpText: '1 = Verbal/paper only  ·  5 = Full PM tool (Buildertrend, simPRO, etc.)',
    weight: 2,
  },
  {
    id: 'ops_project_tool',
    domain: 'operations',
    category: 'Process',
    label: 'Project management tool name',
    type: 'text',
    helpText: 'e.g. Buildertrend, simPRO, Airtable, spreadsheets, none',
    weight: 0,
  },
  {
    id: 'ops_scheduling',
    domain: 'operations',
    category: 'Process',
    label: 'Job scheduling & capacity planning',
    type: 'rating',
    helpText: '1 = Ad hoc / reactive  ·  5 = Formal schedule with resource planning',
    weight: 2,
  },
  {
    id: 'ops_backlog_weeks',
    domain: 'operations',
    category: 'Capacity',
    label: 'Current work backlog (weeks)',
    type: 'number',
    helpText: 'Weeks of signed/committed work ahead',
    weight: 0,
  },
  {
    id: 'ops_equipment',
    domain: 'operations',
    category: 'Capacity',
    label: 'Workshop & equipment condition',
    type: 'rating',
    helpText: '1 = Aging/unreliable  ·  5 = Modern, well-maintained',
    weight: 2,
  },
  {
    id: 'ops_supply_chain',
    domain: 'operations',
    category: 'Capacity',
    label: 'Supplier relationships & supply chain',
    type: 'rating',
    helpText: '1 = Single/unreliable supplier  ·  5 = Multiple reliable suppliers with accounts',
    weight: 2,
  },
  {
    id: 'ops_quality_control',
    domain: 'operations',
    category: 'Quality',
    label: 'Quality control process',
    type: 'rating',
    helpText: '1 = No formal QC  ·  5 = Documented QC with sign-off at each stage',
    weight: 3,
  },
  {
    id: 'ops_defect_rate',
    domain: 'operations',
    category: 'Quality',
    label: 'Rework / defect rate assessment',
    type: 'rating',
    helpText: '1 = Frequent rework/callbacks  ·  5 = Very rare defects',
    weight: 2,
  },
  {
    id: 'ops_staff_count',
    domain: 'operations',
    category: 'Staff',
    label: 'Number of employees (incl. owner)',
    type: 'number',
    weight: 0,
  },
  {
    id: 'ops_staff_qual',
    domain: 'operations',
    category: 'Staff',
    label: 'Staff qualifications & skills',
    type: 'rating',
    helpText: '1 = Mostly unskilled  ·  5 = All licensed tradespeople with current tickets',
    weight: 2,
  },
  {
    id: 'ops_whs',
    domain: 'operations',
    category: 'Compliance',
    label: 'WHS/OHS compliance in place',
    type: 'yesno',
    weight: 3,
  },
  {
    id: 'ops_workers_comp',
    domain: 'operations',
    category: 'Compliance',
    label: 'Workers compensation insurance current',
    type: 'yesno',
    weight: 3,
  },
  {
    id: 'ops_public_liability',
    domain: 'operations',
    category: 'Compliance',
    label: 'Public liability insurance current',
    type: 'yesno',
    weight: 3,
  },
  {
    id: 'ops_qld_license',
    domain: 'operations',
    category: 'Compliance',
    label: 'Queensland contractor/builder licence current',
    type: 'yesno',
    weight: 3,
  },

  // ── SALES ─────────────────────────────────────────────────────────────────
  {
    id: 'sales_crm',
    domain: 'sales',
    category: 'Tools',
    label: 'CRM or quoting tool in use',
    type: 'rating',
    helpText: '1 = Verbal quotes only  ·  5 = Full CRM with pipeline (Tradify, ServiceM8, etc.)',
    weight: 2,
  },
  {
    id: 'sales_crm_tool',
    domain: 'sales',
    category: 'Tools',
    label: 'CRM / quoting tool name',
    type: 'text',
    helpText: 'e.g. Tradify, ServiceM8, HubSpot, spreadsheets, none',
    weight: 0,
  },
  {
    id: 'sales_quote_win',
    domain: 'sales',
    category: 'Performance',
    label: 'Quote-to-win ratio assessment',
    type: 'rating',
    helpText: '1 = <20% win rate  ·  5 = >60% win rate',
    weight: 3,
  },
  {
    id: 'sales_quote_win_pct',
    domain: 'sales',
    category: 'Performance',
    label: 'Approximate quote-to-win rate (%)',
    type: 'number',
    weight: 0,
  },
  {
    id: 'sales_avg_job',
    domain: 'sales',
    category: 'Performance',
    label: 'Average job value (AUD)',
    type: 'number',
    helpText: 'Typical single contract value',
    weight: 0,
  },
  {
    id: 'sales_customer_concentration',
    domain: 'sales',
    category: 'Risk',
    label: 'Customer concentration risk',
    type: 'rating',
    helpText: '1 = >50% from one client (high risk)  ·  5 = Well diversified (<20% per client)',
    weight: 3,
  },
  {
    id: 'sales_top_client_pct',
    domain: 'sales',
    category: 'Risk',
    label: 'Top client as % of revenue',
    type: 'number',
    helpText: 'What % of revenue comes from the largest single customer',
    weight: 0,
  },
  {
    id: 'sales_repeat_business',
    domain: 'sales',
    category: 'Risk',
    label: 'Repeat / returning customer rate',
    type: 'rating',
    helpText: '1 = Almost all one-off projects  ·  5 = Strong ongoing relationships',
    weight: 3,
  },
  {
    id: 'sales_pipeline',
    domain: 'sales',
    category: 'Pipeline',
    label: 'Sales pipeline visibility',
    type: 'rating',
    helpText: '1 = No visibility beyond current job  ·  5 = Clear 3–6 month pipeline',
    weight: 2,
  },
  {
    id: 'sales_contracts',
    domain: 'sales',
    category: 'Pipeline',
    label: 'Formal contracts or POs used',
    type: 'yesno',
    weight: 2,
  },
  {
    id: 'sales_active_clients',
    domain: 'sales',
    category: 'Pipeline',
    label: 'Number of active clients',
    type: 'number',
    weight: 0,
  },

  // ── MARKETING ─────────────────────────────────────────────────────────────
  {
    id: 'mkt_website',
    domain: 'marketing',
    category: 'Online Presence',
    label: 'Website quality & professionalism',
    type: 'rating',
    helpText: '1 = No website  ·  5 = Modern, mobile-friendly site with portfolio',
    weight: 2,
  },
  {
    id: 'mkt_website_url',
    domain: 'marketing',
    category: 'Online Presence',
    label: 'Website URL',
    type: 'text',
    weight: 0,
  },
  {
    id: 'mkt_google_business',
    domain: 'marketing',
    category: 'Online Presence',
    label: 'Google Business Profile active & verified',
    type: 'yesno',
    weight: 2,
  },
  {
    id: 'mkt_google_rating',
    domain: 'marketing',
    category: 'Online Presence',
    label: 'Google review rating (1.0–5.0)',
    type: 'number',
    helpText: 'Current Google star rating',
    weight: 0,
  },
  {
    id: 'mkt_google_reviews_count',
    domain: 'marketing',
    category: 'Online Presence',
    label: 'Number of Google reviews',
    type: 'number',
    weight: 0,
  },
  {
    id: 'mkt_reviews_quality',
    domain: 'marketing',
    category: 'Online Presence',
    label: 'Online reputation assessment',
    type: 'rating',
    helpText: '1 = No/bad reviews  ·  5 = 4.5+ stars with 20+ reviews',
    weight: 2,
  },
  {
    id: 'mkt_social',
    domain: 'marketing',
    category: 'Social Media',
    label: 'Social media presence & activity',
    type: 'rating',
    helpText: '1 = No social presence  ·  5 = Active Instagram/Facebook with regular project posts',
    weight: 1,
  },
  {
    id: 'mkt_lead_gen',
    domain: 'marketing',
    category: 'Lead Generation',
    label: 'Lead generation diversity',
    type: 'rating',
    helpText: '1 = Word of mouth only  ·  5 = Multiple channels (WOM, Google Ads, social, trade networks)',
    weight: 3,
  },
  {
    id: 'mkt_portfolio',
    domain: 'marketing',
    category: 'Lead Generation',
    label: 'Portfolio / showcase of completed work',
    type: 'yesno',
    weight: 2,
  },
  {
    id: 'mkt_marketing_spend_pct',
    domain: 'marketing',
    category: 'Investment',
    label: 'Marketing spend as % of revenue',
    type: 'number',
    helpText: 'Approximate annual marketing budget as % of revenue',
    weight: 0,
  },
]

export function getQuestionsByDomain(domain: Domain): Question[] {
  return QUESTIONS.filter(q => q.domain === domain)
}

export function getCategories(domain: Domain): string[] {
  const qs = getQuestionsByDomain(domain)
  return [...new Set(qs.map(q => q.category))]
}
